apiVersion: v1
kind: Pod
metadata:
  name: demo-duct-tape
  labels:
    app: demo-duct-tape
spec:
  initContainers:
  - name: apply-duct-tape
    image: gcr.io/gcp-dev-tools/duct-tape:latest
    volumeMounts:
    - name: dbg
      mountPath: "/dbg"
  containers:
  - name: helloworld1
    image: busybox
    command: ['sh', '-c', 'echo "The app is running"; ls / /dbg; sleep 3600']
    volumeMounts:
    - name: dbg
      mountPath: "/dbg"
      readOnly: true
  - name: helloworld2
    image: busybox
    command: ['sh', '-c', 'echo "The app is running"; ls / /dbg; sleep 3600']
    volumeMounts:
    - name: dbg
      mountPath: "/dbg"
      readOnly: true
  volumes:
  - name: dbg
    emptyDir: {}
